# Generated by Django 3.0.6 on 2020-05-10 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created', models.DateField()),
                ('title', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('body', models.TextField()),
                ('locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('video', models.URLField()),
                ('score', models.IntegerField(default=0)),
                ('viewed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Event')),
            ],
        ),
    ]
