# Generated by Django 3.0.6 on 2020-05-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='title',
            field=models.CharField(max_length=99),
        ),
    ]
