"""
Django settings for pycon_video_voting project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""


import os
import pathlib

from .common import (
    AUTH_PASSWORD_VALIDATORS, BASE_DIR,
    INSTALLED_APPS, LANGUAGE_CODE, LOGIN_REDIRECT_URL, LOGOUT_REDIRECT_URL,
    MIDDLEWARE, ROOT_URLCONF, SERVER_EMAIL,
    STATIC_ROOT, STATIC_URL, TEMPLATES, TIME_ZONE,
    USE_I18N, USE_L10N, USE_TZ, WSGI_APPLICATION)

ALLOWED_HOSTS = ['pycon-video-voting.herokuapp.com', 'pycon.baypiggies.net']
DEBUG = False

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ['DATABASE_NAME'],
        'USER': os.environ['DATABASE_USER'],
        'PASSWORD': os.environ['DATABASE_PASSWORD'],
        'HOST': 'ec2-18-215-99-63.compute-1.amazonaws.com',
        'PORT': '',
    }
}

