# Generated by Django 3.0.6 on 2020-05-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=120)),
                ('host', models.CharField(help_text='Person who will host', max_length=120)),
                ('meeting_type', models.CharField(max_length=120)),
                ('invitation', models.TextField()),
            ],
        ),
    ]
